name: error-page-template
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  get-template:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@2d70c12368d1958155af4d283f9f21c9a2a8cb98
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
      - uses: actions/checkout@v3
        with:
          repository: 'netlify/internal-shared-templates'
          token: ${{ secrets.GITHUB_TOKEN }}
